### ISSUE TITLE
IE 11 issue

### ISSUE THREAD

**Issue by axeltrip** [mendix/ListenListviewSetter#1]
When using this widget in IE 11 i get the following error:
No constructor found for widget ListenListviewSetter.widget.ListenListviewSetter

**Comment by ateale** [comment]
Hello,
I believe we have the same issue as Anthony.

Whilst running in IE v11.706.1734.0 Mendix v7.16.0 we are getting a no constructor found error.
More details can be found here:

https://support.mendix.com/hc/requests/82970

Regards
Adrian

**Comment by Andries-Smit** [comment]
Issue is resolved, and new version is release, though please note that this widget is no longer needed starting from Mendix version 7.22 as this feature is now part of standard behaviour of the list view
